name: ismn
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.7,<3.12
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - ipykernel
  - pip
  - pip:
     - pygeogrids>=0.3.2
     - configparser
     - tqdm
     - click
     - more_itertools
     - sphinx
     - nbsphinx
     - sphinx_rtd_theme
     - yapf
     - pytest
     - pytest-cov
