#this file is not used at the moment
name: ismn_docs
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - basemap
  - sphinx
  - ipython
  - python=3.6
  - sphinx_rtd_theme
  - pip:
      - pygeogrids
